### ISSUE TITLE
Display Leads

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#10]
Display Leads in Frontend.

User should be able to filter leads on the basis of

1) Category
2) Location
3) Time.

Make sure GUI is user friendly and it's responsive.

**Comment by shubhiD** [comment]
The following interface has been recommended for displaying leads, comments are welcomed, please see the link

https://plus.google.com/u/0/photos/albums/pfjphhmkr1n1os66t8u6kog6mbsmb8jfn?pid=6371014888678588338&oid=114221527942689128228
