### ISSUE TITLE
Improve CSS Tags

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#101]
1. CSS tags such as `input-box, p` etc should never be modified. Assign classes to DOM elements and then create corresponding CSS tags.

2. Don't use generic words such as `cards`. A poorly coded theme/plugin might interfere in live site that has more than 60 plugins.

**Comment by rohitmanglik** [comment]
@vSharique Any update?

**Comment by anantharam** [comment]
These have been taken care of for now.
