### ISSUE TITLE
Transaction History filter by time is currently not working

### ISSUE THREAD

**Issue by anantharam** [EduGorilla/lead-marketplace#105]
In transaction history tab, if we fill the 'Date From' and 'Date To' tab, we should be able to see the transaction within that particular time period, currently that is not happening.

**Comment by Akshat091296** [comment]
Does this issue refer to the backend transaction history tab that I created ?

**Comment by anantharam** [comment]
@Akshat091296 : Yes, the backend tab, can you take a look at this issue?

**Comment by Akshat091296** [comment]
@anantharam Sir, currently there are no entries in the table, if you make some entries, then try again, it will work, I checked it on localhost, it is working fine
