### ISSUE TITLE
EduCash: Transaction history and current status

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#11]
In frontend we have to create an admin portal. This portal can be accessed by both: People who paid us and people who are yet to pay.

1. Those who already paid us, we have to 

a. Show all the leads #10 
b. Allow users to buy them #12 
c. Current status of EduCash 
d. Previously unlocked leads
e. Transaction History

2. Those who are yet to pay us

a. Show all the leads #10 
b. When a user will click on unlock, he should get a buy option. #44 

Create a shortcode to show 

1) current EduCash of the user
2) All the leads unlocked by user
3) Transaction history

**Comment by shubhiD** [comment]
@imayankjoshi  The following timeline layout is proposed for transaction history, please see to it
https://plus.google.com/u/0/photos/albums/pfjphhmkr1n1os66t8u6kog6mbsmb8jfn?pid=6371634229302583538&oid=114221527942689128228

**Comment by imayankjoshi** [comment]
I cannot see the album. It say - "you do not have permission to view this album".

**Comment by shubhiD** [comment]
@imayankjoshi  I dont know what the reason is, please try this link:

https://goo.gl/photos/9KZA11pS3haQhdhs8

**Comment by imayankjoshi** [comment]
it worked. Thank you.

**Comment by anantharam** [comment]
Available here : http://stg3.edugorilla.com/edugorilla_pages_ui/
