### ISSUE TITLE
Improve design of Transaction History

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#110]
I shared it over Google Hangout

**Comment by Akshat091296** [comment]
@rohitmanglik sir, does this issue refer to the backend transaction history tab that I created?

**Comment by rohitmanglik** [comment]
@akshat no, on the frontend side.

**Comment by Akshat091296** [comment]
Okay sir

**Comment by imayankjoshi** [comment]
Can I get the design of new transaction history table.

**Comment by anantharam** [comment]
@rohitmanglik  : Can you share what you had shared with @imayankjoshi in Google Hangouts?

**Comment by rohitmanglik** [comment]
@anantharam Sorry, I am unable to locate it. Can you please try to find in your archive. 

Thanks

**Comment by anantharam** [comment]
Closing this since we are not able to find the new design, and I think the current design is good enough for backend ops team, we can create a new issue if we wish change the design.
