### ISSUE TITLE
Interlink all pages

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#111]
Create a menu to show all the pages of Lead Marketplace.

Leverage inbuilt Wordpress functions to create menus

**Comment by anantharam** [comment]
@rishab1995 : The following shortcodes are currently supported that we need to add as tabs to the main UI :

[edugorilla_leads] - This is the frontend UI for marketing managers to see the some details of possible leads and unlock the contact details by spending EduCash
[educash_payment] - This page shows you the Payment gateway through which the user can buy EduCash
[transaction_history]- This page can be used to view the current client's EduCash Trasncation history
[client_preference_form] - This is to be used by the clients to enter their details and subscribe for email notifications.

**Comment by rohitmanglik** [comment]
First we have to test whether all four shortcodes work fine in same tab.

**Comment by anantharam** [comment]
Available here : http://stg3.edugorilla.com/edugorilla_pages_ui/

**Comment by anantharam** [comment]
Available here : http://stg3.edugorilla.com/edugorilla_pages_ui/
