### ISSUE TITLE
JS Broken: Educash Payment and Manage Preferences

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#136]
When we enter value in Educash payment, nothing changes on screen.

![image](https://cloud.githubusercontent.com/assets/677634/23033059/bbc53430-f49c-11e6-9d3e-44ac93c5bfd4.png)

**Comment by imayankjoshi** [comment]
I don't know what is wrong because it is working fine for me in staging server. link is => http://stg3.edugorilla.com/paynow/

![clip1](https://cloud.githubusercontent.com/assets/24271097/23087617/af7801a8-f59b-11e6-882a-04e3037ff4c1.png)

**Comment by anantharam** [comment]
@imayankjoshi  The second part is still coming up as Total = {{amount*2}} karmas. Can you please check?

**Comment by imayankjoshi** [comment]
You said you can fix the second part.
