### ISSUE TITLE
Unlock Leads - EduCash Deduction is not detected

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#158]
I unlocked a few leads but the EduCash reflected in my account is same.

**Comment by anantharam** [comment]
Educash is getting deducted when we unlock a lead but the frontend transaction history is not showing those transaction correctly, the backend transaction history shows these values correctly. Assigning this to Mayank to fix this.

**Comment by anantharam** [comment]
Since @imayankjoshi was busy with the dislog box change, I have made this change and hence closing this bug.
