### ISSUE TITLE
Invoice template improvements

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/lead-marketplace#61]
When an Institute is notified for purchase, he should get an invoice over email attached.

@anant any template?

**Comment by rohitmanglik** [comment]
Format of Invoice

[INV-1821 (1).pdf](https://github.com/rohitmanglik/lead-marketplace/files/692924/INV-1821.1.pdf)

We might have to make changes in the EduCash deals form to get all the values for PDF.

**Comment by Akshat091296** [comment]
Since the Invoice has been attached, I m closing this issue

**Comment by anantharam** [comment]
@rohitmanglik : How about this template? 
[MyInvoiceTemplate.pdf](https://github.com/EduGorilla/lead-marketplace/files/802042/MyInvoiceTemplate.pdf)
