### ISSUE TITLE
Fix Lead capture Form

### ISSUE THREAD

**Issue by anantharam** [EduGorilla/lead-marketplace#95]
The locations dropdown in the Lead Capture Form currently doesn't support any Indian cities, we need to add Indian cities in the location dropdown and make sure that the form gets submitted properly after selecting the location.

**Comment by rohitmanglik** [comment]
1) To put Indian Cities, you just need to create new listings. It's not constrained wrt country.

2) What all errors are you getting?

**Comment by anantharam** [comment]
![savebuttondisabled](https://cloud.githubusercontent.com/assets/4935838/22404601/2af279f4-e65a-11e6-9b65-c78c0cef3701.jpg)

Save button is disabled.

**Comment by rohitmanglik** [comment]
@anantharam Please verify and close it.
