### ISSUE TITLE
Lead marketplace plugin send error when activate

### ISSUE THREAD

**Issue by tjtarunkumar** [EduGorilla/lead-marketplace#96]
When activate plugin on server it send error "Fatal error: Class 'WP_REST_Controller' not found in /home/softpayer4ucom/public_html/edugorilla/wp-content/plugins/lead-marketplace/frontend/class-Custom-Lead-API.php on line 3".

**Comment by anantharam** [comment]
@tjtarunkumar This issue should be resolved now, can you please check?
http://stg3.edugorilla.com/wp-admin/admin.php?page=edugorilla
